import { act, fireEvent, render, screen, waitFor, cleanup, within } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import MeasurementWorkspace from './MeasurementWorkspace';
import type { MeasurementRepository } from '@/lib/measurementWorkspaceStore';
import type { MeasurementWorkspace as Workspace } from '@/lib/measurementWorkspace';
import { measurementFixture } from '@/test/measurementWorkspaceFixture';
import { addMeasuredPeriod, freezeMeasuredPeriod } from '@/lib/measurementWorkspace';
import { deleteMeasuredPeriod } from '@/lib/measurementLifecycle';

afterEach(cleanup);
beforeEach(() => localStorage.clear());
const actor = { id: 'u', name: 'Engenheiro', canEdit: true };
function fixture() {
  const w: Workspace = { schema: 1, projectId: 'p', projectName: 'Obra isolada', revision: 0, services: [{ id: 's', item: '1.1', description: 'Placas', unit: 'UN', contracted: 100, priceNoBDI: 10, priceWithBDI: 12.5, bdi: 25, importedPrice: true, chapterId: 'c', chapter: 'Prédio', path: 'Prédio › Sinalização', availableFromNumber: 1 }], periods: [1, 2, 3].map(n => ({ id: `m${n}`, number: n, startDate: `2026-0${n}-01`, endDate: `2026-0${n}-28`, status: 'draft' })), entries: [], plans: [], audit: [], importedKeys: [], backupId: 'backup' };
  const repository: MeasurementRepository = { load: vi.fn(async () => w), initialize: vi.fn(async () => w), commit: vi.fn(async next => next), pending: vi.fn(async () => null), pendingSaves: vi.fn(async () => []), archivePending: vi.fn(async () => undefined), drafts: vi.fn(async () => []), writeDraft: vi.fn(async () => undefined), clearDraft: vi.fn(async () => undefined), backup: vi.fn(async () => null) };
  return { w, repository };
}
describe('Tela própria de Medição', () => {
  it('remove o Histórico da tela sem descartar a auditoria armazenada', async () => {
    const { w, repository } = fixture();
    const readAffected = vi.fn();
    const event: Workspace['audit'][number] = {
      id: 'history-event', at: '2026-10-10T12:00:00.000Z', actor: { id: 'u', name: 'Engenheiro' },
      action: 'Editar detalhe', affected: [], before: [], after: [],
    };
    Object.defineProperty(event, 'affected', { get: () => { readAffected(); return []; } });
    w.audit = [event];

    render(<MeasurementWorkspace repository={repository} actor={actor}/>);
    expect(await screen.findByRole('heading', { name: 'Planilha de medição (1 itens)' })).toBeVisible();
    expect(readAffected).not.toHaveBeenCalled();

    expect(screen.queryByRole('button', { name: 'Histórico' })).not.toBeInTheDocument();
    expect(readAffected).not.toHaveBeenCalled();
    expect(w.audit).toHaveLength(1);
  });
  it('mostra a falha de carregamento sem sugerir nova incorporação e permite tentar novamente', async () => {
    const { w, repository } = fixture();
    vi.mocked(repository.load).mockRejectedValueOnce(new Error('canceling statement due to statement timeout')).mockResolvedValue(w);
    render(<MeasurementWorkspace repository={repository} actor={actor}/>);
    expect(await screen.findByRole('alert')).toHaveTextContent('canceling statement due to statement timeout');
    expect(screen.getByRole('heading', { name: 'Não foi possível carregar a Medição' })).toBeVisible();
    expect(screen.queryByText('Incorporar a base de Medição')).not.toBeInTheDocument();
    fireEvent.click(screen.getByRole('button', { name: 'Tentar carregar novamente' }));
    expect(await screen.findByRole('heading', { name: 'Planilha de medição (1 itens)' })).toBeVisible();
    expect(repository.load).toHaveBeenCalledTimes(2);
    expect(repository.commit).not.toHaveBeenCalled();
  });
  it('evita reenvio fiscal duplicado e libera novo envio após uma correção', async () => {
    const { w, repository } = fixture();
    const sent = freezeMeasuredPeriod(w, { ...actor, canReview: true }, 'm1');
    vi.mocked(repository.load).mockResolvedValue(sent);
    render(<MeasurementWorkspace repository={repository} actor={{ ...actor, canReview: true }}/>);
    const resend = await screen.findByRole('button', { name: 'Reenviar para fiscalização' });
    expect(resend).toBeDisabled();
    expect(repository.commit).not.toHaveBeenCalled();
    const quantity = screen.getByRole('spinbutton', { name: 'Quantidade de Placas' });
    fireEvent.change(quantity, { target: { value: '1' } }); fireEvent.blur(quantity);
    await waitFor(() => expect(resend).toBeEnabled());
    fireEvent.click(resend);
    let dialog = screen.getByRole('dialog');
    expect(within(dialog).getByText('Esta medição possui avisos antes do envio')).toBeVisible();
    expect(repository.commit).toHaveBeenCalledTimes(1);
    fireEvent.click(within(dialog).getByRole('button', { name: 'Cancelar' }));
    expect(repository.commit).toHaveBeenCalledTimes(1);
    fireEvent.click(resend);
    dialog = screen.getByRole('dialog');
    fireEvent.click(within(dialog).getByRole('button', { name: 'Confirmar envio' }));
    await waitFor(() => expect(repository.commit).toHaveBeenCalledTimes(2));
    const updated = vi.mocked(repository.commit).mock.calls.at(-1)![0];
    expect(updated.periods[0].status).toBe('in_review');
    expect(updated.periods[0].frozen?.[0].qty).toBe(1);
    expect(resend).toBeDisabled();
  });
  it('confirma o período antes do primeiro envio e cancelar não altera a medição', async () => {
    const { w, repository } = fixture();
    w.periods = [{ id: 'm1', number: 1, startDate: '2026-08-24', endDate: '2026-09-29', status: 'draft' }];
    w.entries = [{ projectId: 'p', measurementId: 'm1', serviceId: 's', rows: [{ id: 'first', location: '', comment: '', formula: 'STANDARD', multiplier: 1, measuredQuantity: 0 }] }];
    render(<MeasurementWorkspace repository={repository} actor={{ ...actor, canReview: true }}/>);
    const send = await screen.findByRole('button', { name: 'Enviar para fiscalização' });
    fireEvent.click(send);
    let dialog = screen.getByRole('dialog');
    expect(within(dialog).getByText('Esta medição possui avisos antes do envio')).toBeVisible();
    expect(within(dialog).getByText(/24\/08\/2026 a 29\/09\/2026/)).toBeVisible();
    expect(within(dialog).getByText(/Ao confirmar, você envia a medição mesmo com estes avisos/)).toBeVisible();
    fireEvent.click(within(dialog).getByRole('button', { name: 'Cancelar' }));
    expect(repository.commit).not.toHaveBeenCalled();
    fireEvent.click(send);
    dialog = screen.getByRole('dialog');
    fireEvent.click(within(dialog).getByRole('button', { name: 'Confirmar envio' }));
    await waitFor(() => expect(repository.commit).toHaveBeenCalledTimes(1));
    expect(vi.mocked(repository.commit).mock.calls[0][0].periods[0].status).toBe('in_review');
    expect(w.periods[0].status).toBe('draft');
  });
  it('bloqueia envio sem quantitativos e não grava o período', async () => {
    const { repository } = fixture();
    render(<MeasurementWorkspace repository={repository} actor={{ ...actor, canReview: true }}/>);
    fireEvent.click(await screen.findByRole('button', { name: 'Enviar para fiscalização' }));
    const dialog = screen.getByRole('dialog');
    expect(within(dialog).getByText('Não é possível enviar para fiscalização')).toBeVisible();
    expect(within(dialog).getByText(/Não há itens medidos neste período/)).toBeVisible();
    expect(within(dialog).getByRole('button', { name: 'Confirmar envio' })).toBeDisabled();
    expect(repository.commit).not.toHaveBeenCalled();
  });
  it('valida somente a medição selecionada antes do envio, sem reaproveitar a anterior', async () => {
    const { w, repository } = fixture();
    w.entries = [{ projectId: 'p', measurementId: 'm1', serviceId: 's', rows: [{ id: 'first', location: '', comment: '', formula: 'STANDARD', multiplier: 5, measuredQuantity: 0 }] }];
    render(<MeasurementWorkspace repository={repository} actor={{ ...actor, canReview: true }}/>);
    fireEvent.change(await screen.findByLabelText('Medição selecionada'), { target: { value: 'm2' } });
    fireEvent.click(screen.getByRole('button', { name: 'Enviar para fiscalização' }));
    const dialog = screen.getByRole('dialog');
    expect(within(dialog).getByText(/Não há itens medidos neste período/)).toBeVisible();
    expect(within(dialog).getByRole('button', { name: 'Confirmar envio' })).toBeDisabled();
    expect(repository.commit).not.toHaveBeenCalled();
  });
  it('deixa abrir o envio e trocar de período, mas não omite rascunhos na confirmação fiscal', async () => {
    const { w, repository } = fixture();
    w.periods = [
      { id: 'm1', number: 1, startDate: '2026-08-24', endDate: '2026-09-29', status: 'draft' },
      { id: 'm2', number: 2, startDate: '2026-09-30', endDate: '2026-10-29', status: 'draft' },
    ];
    w.entries = ['m1', 'm2'].map(measurementId => ({ projectId: 'p', measurementId, serviceId: 's', rows: [{ id: `${measurementId}-row`, location: '', comment: '', formula: 'STANDARD' as const, multiplier: 1, measuredQuantity: 0 }] }));
    vi.mocked(repository.drafts).mockResolvedValue([{ projectId: 'p', measurementId: 'm1', serviceId: 's', rowId: 'm1-row', changes: { multiplier: '3' } }]);
    render(<MeasurementWorkspace repository={repository} actor={{ ...actor, canReview: true }}/>);
    const send = await screen.findByRole('button', { name: 'Enviar para fiscalização' });
    expect(send).toBeEnabled();
    expect(screen.queryByText(/Finalize ou recupere os campos antes de enviar para fiscalização/)).not.toBeInTheDocument();
    fireEvent.click(send);
    fireEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Confirmar envio' }));
    expect((await screen.findAllByText(/nenhum quantitativo será omitido/))[0]).toBeVisible();
    expect(repository.commit).not.toHaveBeenCalled();
    fireEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Cancelar' }));
    fireEvent.click(screen.getByRole('button', { name: 'Nova medição' }));
    expect(within(screen.getByRole('dialog')).getByText('30/10/2026 a 28/11/2026')).toBeVisible();
    fireEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Cancelar' }));
    fireEvent.change(screen.getByLabelText('Medição selecionada'), { target: { value: 'm2' } });
    expect(send).toBeEnabled();
    expect(screen.queryByText(/Finalize ou recupere os campos antes de enviar para fiscalização/)).not.toBeInTheDocument();
    expect(repository.commit).not.toHaveBeenCalled();
  });
  it('recebe tempo real, preserva medição e painel selecionados e espera sair da célula', async () => {
    const { w, repository } = fixture(); let notice!: (revision: number) => void;
    repository.remoteRevision = vi.fn(async () => 0);
    repository.watch = (n, c) => { notice = n; c(true); return vi.fn(); };
    render(<MeasurementWorkspace repository={repository} actor={actor}/>);
    fireEvent.change(await screen.findByLabelText('Medição selecionada'), { target: { value: 'm2' } });
    const quantity = screen.getByLabelText('Quantidade de Placas');
    act(() => quantity.focus()); fireEvent.click(quantity);
    const remote = { ...structuredClone(w), revision: 1, entries: [{ projectId: 'p', measurementId: 'm2', serviceId: 's', rows: [{ id: 'remote', location: '', comment: 'Outro computador', formula: 'STANDARD' as const, multiplier: 5, measuredQuantity: 0 }] }] };
    vi.mocked(repository.load).mockResolvedValue(remote);
    act(() => notice(1)); await screen.findByText('Atualização recebida · rascunho preservado');
    expect(quantity).toHaveValue(0); expect(repository.load).toHaveBeenCalledOnce();
    act(() => quantity.blur());
    await waitFor(() => expect(screen.getByLabelText('Quantidade de Placas')).toHaveValue(5));
    expect(screen.getByLabelText('Medição selecionada')).toHaveValue('m2');
    expect(screen.getByText('Detalhe de quantitativos · 2ª medição')).toBeVisible();
    expect(repository.commit).not.toHaveBeenCalled();
    expect(await screen.findByText('Atualizado · Tempo real ativo')).toBeVisible();
  });
  it('aviso remoto não apaga o número em digitação nem seu rascunho e mantém proteção de conflito', async () => {
    const { repository } = fixture(); let notice!: (revision: number) => void;
    repository.remoteRevision = vi.fn(async () => 0);
    repository.watch = (n, c) => { notice = n; c(true); return vi.fn(); };
    vi.mocked(repository.commit).mockRejectedValue(new Error('Conflito de revisão'));
    render(<MeasurementWorkspace repository={repository} actor={actor}/>);
    const quantity = await screen.findByLabelText('Quantidade de Placas');
    act(() => quantity.focus()); fireEvent.change(quantity, { target: { value: '3' } });
    act(() => notice(1)); await screen.findByText('Atualização recebida · rascunho preservado');
    expect(quantity).toHaveValue(3); expect(repository.load).toHaveBeenCalledOnce();
    act(() => quantity.blur()); await screen.findByText('Não salvo · rascunho preservado');
    expect(repository.clearDraft).not.toHaveBeenCalled();
    expect(repository.writeDraft).toHaveBeenCalledWith(expect.objectContaining({ changes: { multiplier: '3' } }));
    expect(screen.getByLabelText('Medição selecionada')).toBeEnabled();
  });
  it('recupera exclusão pendente e seleciona uma medição que ainda existe', async () => {
    const { w, repository } = fixture();
    const view = render(<MeasurementWorkspace repository={repository} actor={actor}/>);
    fireEvent.change(await screen.findByLabelText('Medição selecionada'), { target: { value: 'm3' } });
    view.unmount();
    const candidate = deleteMeasuredPeriod(w, actor, 'm3', 'Remover teste');
    vi.mocked(repository.pending).mockResolvedValue({ baseRevision: w.revision, candidate });
    render(<MeasurementWorkspace repository={repository} actor={actor}/>);
    expect(await screen.findByLabelText('Medição selecionada')).toHaveValue('m3');
    await waitFor(() => expect(screen.getByLabelText('Medição selecionada')).toHaveValue('m2'));
    expect(screen.getByRole('button', { name: 'Restaurar medição excluída' })).toBeVisible();
    expect(screen.getByRole('heading', { name: 'Planilha de medição (1 itens)' })).toBeVisible();
  });
  it('permite excluir e restaurar pelo controle contextual e editar a primeira até registrar aprovação', async () => {
    const { w, repository } = fixture(); const reviewer = { ...actor, canReview: true };
    w.periods = [{ id: 'm1', number: 1, startDate: '2026-08-24', endDate: '2026-09-29', status: 'draft' }];
    w.entries = [{ projectId: 'p', measurementId: 'm1', serviceId: 's', rows: [{ id: 'r', location: '', comment: 'Preservado', formula: 'STANDARD', multiplier: 29, measuredQuantity: 0 }] }];
    const base = addMeasuredPeriod(freezeMeasuredPeriod(w, reviewer, 'm1'), reviewer), second = base.periods[1].id;
    vi.mocked(repository.load).mockResolvedValue(base);
    render(<MeasurementWorkspace repository={repository} actor={reviewer}/>);
    fireEvent.change(await screen.findByLabelText('Medição selecionada'), { target: { value: second } });
    fireEvent.click(screen.getByRole('button', { name: 'Excluir medição' }));
    let dialog = screen.getByRole('dialog');
    expect(repository.commit).not.toHaveBeenCalled();
    fireEvent.change(within(dialog).getByLabelText('Motivo da operação'), { target: { value: 'Medição criada para teste' } });
    fireEvent.click(within(dialog).getByRole('button', { name: 'Excluir medição' }));
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument());
    expect(screen.getByLabelText('Medição selecionada')).toHaveValue('m1');
    expect(screen.getByRole('button', { name: 'Excluir medição' })).toBeDisabled();
    let saved = vi.mocked(repository.commit).mock.calls.at(-1)![0];
    expect(saved.entries).toEqual(base.entries); expect(saved.periods[0]).toEqual(base.periods[0]);
    fireEvent.click(screen.getByRole('button', { name: 'Restaurar medição excluída' }));
    dialog = screen.getByRole('dialog');
    fireEvent.change(within(dialog).getByLabelText('Motivo da operação'), { target: { value: 'Recuperar período' } });
    fireEvent.click(within(dialog).getByRole('button', { name: 'Restaurar medição' }));
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument());
    expect(screen.getByLabelText('Medição selecionada')).toHaveValue(second);
    fireEvent.change(screen.getByLabelText('Medição selecionada'), { target: { value: 'm1' } });
    expect(screen.getByRole('spinbutton', { name: 'Quantidade de Placas' })).toBeEnabled();
    expect(screen.getByRole('textbox', { name: 'Nº da ART' })).toBeEnabled();
    fireEvent.click(screen.getByRole('button', { name: 'Aprovado pela fiscalização' }));
    dialog = screen.getByRole('dialog');
    fireEvent.click(within(dialog).getByRole('button', { name: 'Cancelar' }));
    expect(screen.getByRole('spinbutton', { name: 'Quantidade de Placas' })).toBeEnabled();
    fireEvent.click(screen.getByRole('button', { name: 'Aprovado pela fiscalização' }));
    fireEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Aprovado pela fiscalização' }));
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument());
    saved = vi.mocked(repository.commit).mock.calls.at(-1)![0];
    expect(saved.entries).toEqual(base.entries); expect(saved.periods[0].status).toBe('approved');
    expect(screen.getByRole('spinbutton', { name: 'Quantidade de Placas' })).toHaveAttribute('readonly');
    expect(screen.getByRole('textbox', { name: 'Nº da ART' })).toBeDisabled();
    expect(screen.queryByRole('button', { name: 'Reabrir para correção' })).not.toBeInTheDocument();
  });
  it('cancelar exclusão não grava; falha de confirmação mantém período e rascunho', async () => {
    const { repository } = fixture(); render(<MeasurementWorkspace repository={repository} actor={actor}/>);
    fireEvent.change(await screen.findByLabelText('Medição selecionada'), { target: { value: 'm3' } });
    fireEvent.click(screen.getByRole('button', { name: 'Excluir medição' }));
    fireEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Cancelar' }));
    expect(repository.commit).not.toHaveBeenCalled();
    vi.mocked(repository.commit).mockRejectedValue(new Error('Sem conexão'));
    fireEvent.click(screen.getByRole('button', { name: 'Excluir medição' }));
    const dialog = screen.getByRole('dialog');
    fireEvent.change(within(dialog).getByLabelText('Motivo da operação'), { target: { value: 'Teste' } });
    fireEvent.click(within(dialog).getByRole('button', { name: 'Excluir medição' }));
    await waitFor(() => expect(within(dialog).getByRole('alert')).toHaveTextContent('Sem conexão'));
    expect(screen.getByLabelText('Medição selecionada')).toHaveValue('m3');
    expect(repository.clearDraft).not.toHaveBeenCalled();
  });
  it('reabre a medição selecionada após recarga sem salvar a obra e isola a preferência por usuário', async () => {
    const { repository } = fixture();
    let view = render(<MeasurementWorkspace repository={repository} actor={actor}/>);
    fireEvent.change(await screen.findByLabelText('Medição selecionada'), { target: { value: 'm2' } });
    view.unmount();
    view = render(<MeasurementWorkspace repository={repository} actor={actor}/>);
    expect(await screen.findByLabelText('Medição selecionada')).toHaveValue('m2');
    expect(screen.getByLabelText('Medição nº')).toHaveValue('2');
    expect(screen.getByRole('region', { name: 'Painel inferior de quantitativos' })).toHaveTextContent(/^$/);
    expect(repository.commit).not.toHaveBeenCalled();
    view.unmount();
    render(<MeasurementWorkspace repository={repository} actor={{ ...actor, id: 'outro-usuario' }}/>);
    expect(await screen.findByLabelText('Medição selecionada')).toHaveValue('m1');
  });
  it('mantém o número do boletim somente para leitura e ignora rascunho antigo de renumeração', async () => {
    const { repository } = fixture();
    vi.mocked(repository.drafts).mockResolvedValue([{ projectId: 'p', measurementId: 'm1', serviceId: '__bulletin__', rowId: 'number', changes: { value: '5' } }]);
    render(<MeasurementWorkspace repository={repository} actor={actor}/>);
    const number = await screen.findByRole('textbox', { name: 'Medição nº' });
    expect(number).toHaveValue('1');
    expect(number).toHaveAttribute('readonly');
    fireEvent.blur(number);
    expect(repository.commit).not.toHaveBeenCalled();
    expect(repository.clearDraft).not.toHaveBeenCalled();
  });
  it('calcula a segunda medição sem datas manuais e identifica o novo boletim sem copiar quantidades', async () => {
    const { w, repository } = fixture();
    w.periods = [{ id: 'm1', number: 1, startDate: '2026-08-24', endDate: '2026-09-29', status: 'draft' }];
    w.entries = [{ projectId: 'p', measurementId: 'm1', serviceId: 's', rows: [{ id: 'row1', location: '', comment: 'Preservado', formula: 'STANDARD', multiplier: 29, measuredQuantity: 0 }] }];
    const before = structuredClone(w);
    const view = render(<MeasurementWorkspace repository={repository} actor={actor}/>);
    fireEvent.click(await screen.findByRole('button', { name: 'Nova medição' }));
    const dialog = screen.getByRole('dialog');
    expect(within(dialog).getByText('30/09/2026 a 29/10/2026')).toBeVisible();
    expect(dialog.querySelector('input')).toBeNull();
    fireEvent.click(within(dialog).getByRole('button', { name: 'Criar medição' }));
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument());
    const saved = vi.mocked(repository.commit).mock.calls[0][0];
    expect(saved.periods[0]).toEqual(before.periods[0]);
    expect(saved.entries).toEqual(before.entries);
    expect(screen.getByRole('combobox', { name: 'Medição selecionada' })).toHaveValue(saved.periods[1].id);
    expect(screen.getByRole('textbox', { name: 'Medição nº' })).toHaveValue('2');
    expect(screen.getByRole('spinbutton', { name: 'Quantidade de Placas' })).toHaveValue(0);
    fireEvent.click(screen.getByRole('spinbutton', { name: 'Quantidade de Placas' }));
    expect(screen.getByText('Detalhe de quantitativos · 2ª medição')).toBeVisible();
    vi.mocked(repository.load).mockResolvedValue(saved);
    view.unmount(); render(<MeasurementWorkspace repository={repository} actor={actor}/>);
    expect(await screen.findByLabelText('Medição selecionada')).toHaveValue(saved.periods[1].id);
  });
  it('reintegra o boletim acima dos painéis e salva somente ao sair do campo', async () => {
    const { w, repository } = fixture();
    w.contract = { contractor: 'Cliente', contracted: 'Empresa', artNumber: 'Original', bdiPercent: 25 };
    const view = render(<MeasurementWorkspace repository={repository} actor={actor}/>);
    const field = await screen.findByLabelText('Nº da ART');
    const bulletin = screen.getByRole('region', { name: 'Boletim de medição para pagamento' });
    const sheet = screen.getByRole('region', { name: 'Planilha da medição atual' });
    expect(bulletin.compareDocumentPosition(sheet) & Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy();
    for (const label of ['Contratante', 'Contratada', 'Obra', 'Local / Município', 'Objeto', 'Nº do contrato', 'Fonte de Orçamento', 'BDI %', 'Medição nº']) expect(within(bulletin).getByLabelText(label)).toBeEnabled();
    expect(bulletin).toHaveTextContent('Período da Medição');
    expect(bulletin).toHaveTextContent('Data de Emissão');
    fireEvent.change(field, { target: { value: 'ART revisada' } });
    expect(repository.commit).not.toHaveBeenCalled();
    fireEvent.blur(field);
    await waitFor(() => expect(repository.clearDraft).toHaveBeenCalledWith('m1', '__bulletin__', 'artNumber'));
    const saved = vi.mocked(repository.commit).mock.calls.at(-1)![0];
    expect(saved.periods[0].bulletin?.contract.artNumber).toBe('ART revisada');
    expect(saved.entries).toEqual(w.entries);
    expect(saved.services).toEqual(w.services);
    fireEvent.change(screen.getByLabelText('Medição selecionada'), { target: { value: 'm2' } });
    expect(screen.getByLabelText('Nº da ART')).toHaveValue('Original');
    fireEvent.change(screen.getByLabelText('Medição selecionada'), { target: { value: 'm1' } });
    expect(screen.getByLabelText('Nº da ART')).toHaveValue('ART revisada');
    vi.mocked(repository.load).mockResolvedValue(saved);
    view.unmount();
    render(<MeasurementWorkspace repository={repository} actor={actor}/>);
    expect(await screen.findByLabelText('Nº da ART')).toHaveValue('ART revisada');
    expect(screen.queryByRole('button', { name: /Histórico/ })).not.toBeInTheDocument();
    expect(saved.audit.some(event => event.action.includes('Editar boletim'))).toBe(true);
  });
  it('mantém rascunho do boletim na falha e recupera o campo após recarga', async () => {
    const { repository } = fixture();
    vi.mocked(repository.commit).mockRejectedValue(new Error('Falha simulada'));
    const view = render(<MeasurementWorkspace repository={repository} actor={actor}/>);
    const field = await screen.findByLabelText('Objeto');
    fireEvent.change(field, { target: { value: 'Escopo pendente' } }); fireEvent.blur(field);
    await screen.findByText('Não salvo · rascunho preservado');
    expect(repository.clearDraft).not.toHaveBeenCalled();
    expect(field).toHaveValue('Escopo pendente');
    vi.mocked(repository.drafts).mockResolvedValue([{ projectId: 'p', measurementId: 'm1', serviceId: '__bulletin__', rowId: 'contractObject', changes: { value: 'Escopo pendente' } }]);
    view.unmount(); render(<MeasurementWorkspace repository={repository} actor={actor}/>);
    expect(await screen.findByLabelText('Objeto')).toHaveValue('Escopo pendente');
    expect(screen.queryByRole('button', { name: 'Recuperar rascunho' })).not.toBeInTheDocument();
  });
  it('reserva a gravação no blur mesmo com rascunho lento e não permite congelar o cabeçalho antigo', async () => {
    const { repository } = fixture(); let finishDraft!: () => void, finishSave!: (w: Workspace) => void;
    vi.mocked(repository.writeDraft).mockImplementation(() => new Promise(resolve => { finishDraft = resolve; }));
    vi.mocked(repository.commit).mockImplementation(() => new Promise(resolve => { finishSave = resolve; }));
    render(<MeasurementWorkspace repository={repository} actor={{ ...actor, canReview: true }}/>);
    const field = await screen.findByLabelText('Nº da ART');
    fireEvent.change(field, { target: { value: 'ART pendente' } });
    await waitFor(() => expect(repository.writeDraft).toHaveBeenCalled());
    fireEvent.blur(field);
    expect(screen.getByRole('button', { name: 'Enviar para fiscalização' })).toBeEnabled();
    expect(screen.getByLabelText('Medição selecionada')).toBeEnabled();
    fireEvent.click(screen.getByRole('button', { name: 'Enviar para fiscalização' }));
    await waitFor(() => expect(repository.commit).toHaveBeenCalledTimes(1));
    const candidate = vi.mocked(repository.commit).mock.calls[0][0];
    expect(candidate.periods[0].status).toBe('draft');
    expect(candidate.periods[0].bulletin?.contract.artNumber).toBe('ART pendente');
    await act(async () => { finishSave(candidate); });
    expect(repository.clearDraft).not.toHaveBeenCalled();
    await act(async () => { finishDraft(); });
    await waitFor(() => expect(repository.clearDraft).toHaveBeenCalledWith('m1', '__bulletin__', 'artNumber'));
  });
  it('boletim de período fiscal fica legível sem permitir alterações', async () => {
    const { w, repository } = fixture(); w.periods[0].status = 'approved';
    render(<MeasurementWorkspace repository={repository} actor={actor}/>);
    expect(await screen.findByLabelText('Obra')).toBeDisabled();
    expect(screen.getByLabelText('Nº da ART')).toBeDisabled();
    expect(screen.getByLabelText('BDI %')).toBeDisabled();
    expect(repository.commit).not.toHaveBeenCalled();
  });

  it('mantém os resumos no final da planilha e a comparação do planejamento somente em leitura', async () => {
    const { w, repository } = fixture();
    w.entries = [{ projectId: 'p', measurementId: 'm1', serviceId: 's', rows: [{ id: 'kept', location: '', comment: 'Registro preservado', formula: 'STANDARD', multiplier: 20, measuredQuantity: 0 }] }];
    render(<MeasurementWorkspace repository={repository} actor={actor} forecastByPeriod={[{ number: 1, startDate: '2026-01-01', endDate: '2026-01-28', value: 500 }]}/>);
    const summary = await screen.findByRole('region', { name: 'Resumo financeiro da medição completa' });
    const sheet = screen.getByRole('region', { name: 'Planilha da medição atual' });
    expect(sheet).toContainElement(summary);
    expect(within(summary).getByRole('heading', { name: 'Sem BDI' })).toBeInTheDocument();
    expect(within(summary).getByRole('heading', { name: 'BDI (25.00%)' })).toBeInTheDocument();
    expect(within(summary).getByRole('heading', { name: 'Com BDI' })).toBeInTheDocument();
    expect(summary).toHaveTextContent('20.00%');
    expect(within(summary).getByTestId('forecast-period')).toHaveTextContent('500,00');
    expect(within(summary).getByTestId('forecast-difference')).toHaveTextContent('-R$ 250,00');
    fireEvent.click(screen.getByRole('button', { name: /Prédio/ }));
    expect(summary).toHaveTextContent('20.00%');
    fireEvent.change(screen.getByLabelText('Medição selecionada'), { target: { value: 'm2' } });
    expect(within(summary).getByTestId('forecast-period')).toHaveTextContent('Não disponível');
    expect(within(summary).getByTestId('forecast-difference')).toHaveTextContent('Não disponível');
    expect(repository.commit).not.toHaveBeenCalled();
  });
  it('mantém os dois painéis ao recolher capítulos e reabre o detalhe sem alterar os quantitativos', async () => {
    const { w, repository } = fixture();
    w.entries = [{ projectId: 'p', measurementId: 'm1', serviceId: 's', rows: [{ id: 'kept', location: '', comment: 'Registro preservado', formula: 'STANDARD', multiplier: 7, measuredQuantity: 0, origin: { kind: 'manual' } }] }];
    render(<MeasurementWorkspace repository={repository} actor={actor}/>);
    const quantity = await screen.findByLabelText('Quantidade de Placas');
    fireEvent.click(quantity);
    const sheet = screen.getByRole('region', { name: 'Planilha da medição atual' });
    const detail = screen.getByRole('region', { name: 'Painel inferior de quantitativos' });
    const divider = screen.getByRole('separator', { name: 'Ajustar altura da planilha e do detalhe' });
    const chapter = within(sheet).getByRole('button', { name: /Prédio/ });
    fireEvent.click(chapter);
    expect(sheet).toBeInTheDocument();
    expect(divider).toBeInTheDocument();
    expect(detail).toHaveTextContent(/^$/);
    expect(screen.queryByLabelText('Quantidade de Placas')).not.toBeInTheDocument();
    expect(within(sheet).getByText('Total Geral')).toBeVisible();
    fireEvent.click(chapter);
    const restoredQuantity = screen.getByLabelText('Quantidade de Placas');
    expect(restoredQuantity).toHaveValue(7);
    fireEvent.click(restoredQuantity);
    expect(within(detail).getByLabelText('Comentário da linha 1')).toHaveValue('Registro preservado');
    expect(repository.commit).not.toHaveBeenCalled();
  });
  it('mantém capítulo e subcapítulo recolhidos ao trocar de medição e voltar à página', async () => {
    const { w, repository } = fixture();
    w.entries = [{ projectId: 'p', measurementId: 'm1', serviceId: 's', rows: [{ id: 'kept', location: '', comment: 'Registro preservado', formula: 'STANDARD', multiplier: 7, measuredQuantity: 0, origin: { kind: 'manual' } }] }];
    const originalEntries = structuredClone(w.entries);
    let view = render(<MeasurementWorkspace repository={repository} actor={actor}/>);

    const sheet = await screen.findByRole('region', { name: 'Planilha da medição atual' });
    fireEvent.click(within(sheet).getByRole('button', { name: /Sinalização/ }));
    expect(screen.queryByLabelText('Quantidade de Placas')).not.toBeInTheDocument();
    fireEvent.click(within(sheet).getByRole('button', { name: /Prédio/ }));
    expect(within(sheet).queryByRole('button', { name: /Sinalização/ })).not.toBeInTheDocument();

    fireEvent.change(screen.getByLabelText('Medição selecionada'), { target: { value: 'm2' } });
    expect(within(sheet).queryByRole('button', { name: /Sinalização/ })).not.toBeInTheDocument();
    fireEvent.change(screen.getByLabelText('Medição selecionada'), { target: { value: 'm1' } });
    expect(within(sheet).queryByRole('button', { name: /Sinalização/ })).not.toBeInTheDocument();

    view.unmount();
    view = render(<MeasurementWorkspace repository={repository} actor={actor}/>);
    const reopenedSheet = await screen.findByRole('region', { name: 'Planilha da medição atual' });
    expect(within(reopenedSheet).queryByRole('button', { name: /Sinalização/ })).not.toBeInTheDocument();
    fireEvent.click(within(reopenedSheet).getByRole('button', { name: /Prédio/ }));
    expect(within(reopenedSheet).getByRole('button', { name: /Sinalização/ })).toBeVisible();
    expect(screen.queryByLabelText('Quantidade de Placas')).not.toBeInTheDocument();
    fireEvent.click(within(reopenedSheet).getByRole('button', { name: /Sinalização/ }));
    expect(screen.getByLabelText('Quantidade de Placas')).toHaveValue(7);
    expect(w.entries).toEqual(originalEntries);
    expect(repository.commit).not.toHaveBeenCalled();
    view.unmount();
  });
  it('isola capítulos recolhidos por usuário e obra sem salvar essa preferência na nuvem', async () => {
    const { w, repository } = fixture();
    let view = render(<MeasurementWorkspace repository={repository} actor={actor}/>);
    const sheet = await screen.findByRole('region', { name: 'Planilha da medição atual' });
    fireEvent.click(within(sheet).getByRole('button', { name: /Prédio/ }));
    expect(screen.queryByLabelText('Quantidade de Placas')).not.toBeInTheDocument();
    view.unmount();

    view = render(<MeasurementWorkspace repository={repository} actor={{ ...actor, id: 'outro-usuario' }}/>);
    expect(await screen.findByLabelText('Quantidade de Placas')).toBeInTheDocument();
    view.unmount();

    vi.mocked(repository.load).mockResolvedValue({ ...w, projectId: 'outra-obra', projectName: 'Outra obra' });
    view = render(<MeasurementWorkspace repository={repository} actor={actor}/>);
    expect(await screen.findByLabelText('Quantidade de Placas')).toBeInTheDocument();
    expect(repository.commit).not.toHaveBeenCalled();
    view.unmount();
  });
  it('limpa o painel ao clicar fora da quantidade, preservando cliques e rascunhos dentro do editor', async () => {
    const { w, repository } = fixture();
    w.services.push({ ...w.services[0], id: 's2', description: 'Outra tarefa' });
    render(<MeasurementWorkspace repository={repository} actor={actor}/>);
    const quantity = await screen.findByLabelText('Quantidade de Placas');
    const panel = screen.getByRole('region', { name: 'Painel inferior de quantitativos' });
    const cells = within(screen.getByTestId('service-s2')).getAllByRole('cell');
    for (const index of [0, 3, 5, 8, 10, 11, 12, 13, 14]) {
      fireEvent.click(quantity);
      expect(within(panel).getByLabelText('Unidades da linha 1')).toBeVisible();
      fireEvent.click(cells[index]);
      expect(panel).toHaveTextContent(/^$/);
    }
    fireEvent.click(quantity);
    expect(within(panel).queryByText('Placas', { exact: true })).not.toBeInTheDocument();
    const a = within(panel).getByLabelText('Unidades da linha 1');
    fireEvent.click(a);
    fireEvent.change(a, { target: { value: '3' } });
    expect(repository.commit).not.toHaveBeenCalled();
    fireEvent.blur(a);
    fireEvent.click(cells[11]);
    await waitFor(() => expect(screen.getByLabelText('Quantidade de Placas')).toHaveValue(3));
    await waitFor(() => expect(screen.getByRole('status')).toHaveTextContent('Salvo neste navegador'));
    fireEvent.click(cells[11]);
    expect(panel).toHaveTextContent(/^$/);
    const saved = vi.mocked(repository.commit).mock.calls.at(-1)![0];
    expect(saved.entries[0]).toMatchObject({ measurementId: 'm1', serviceId: 's' });
    expect(saved.services.map(s => s.contracted)).toEqual([100, 100]);
    fireEvent.click(screen.getByLabelText('Quantidade de Placas'));
    expect(within(panel).getByLabelText('Unidades da linha 1')).toHaveValue(3);
    fireEvent.click(within(panel).getByLabelText('Comentário da linha 1'));
    expect(within(panel).getByLabelText('Unidades da linha 1')).toBeVisible();
  });
  it('abre a composição pela descrição em leitura e mantém o painel de quantitativos vazio', async () => {
    const { w, repository } = fixture();
    const { project } = measurementFixture();
    w.services[0].sourceTaskId = 'signs';
    w.services[0].sourceBudgetId = 'budget-signs';
    const before = structuredClone(project);
    render(<MeasurementWorkspace repository={repository} actor={actor} analyticProject={project}/>);
    fireEvent.click(await screen.findByLabelText('Quantidade de Placas'));
    fireEvent.click(screen.getByRole('button', { name: 'Ver composição analítica de Placas' }));
    const analytic = screen.getByRole('region', { name: 'Composição analítica de Placas' });
    expect(analytic).toHaveTextContent('Placa de sinalização · insumo fictício');
    expect(within(analytic).getAllByRole('columnheader')).toHaveLength(8);
    expect(within(analytic).queryByRole('spinbutton')).not.toBeInTheDocument();
    expect(screen.getByRole('region', { name: 'Painel inferior de quantitativos' })).toHaveTextContent(/^$/);
    expect(repository.commit).not.toHaveBeenCalled();
    expect(project).toEqual(before);
    fireEvent.click(screen.getByLabelText('Quantidade de Placas'));
    expect(screen.queryByRole('region', { name: 'Composição analítica de Placas' })).not.toBeInTheDocument();
    expect(screen.getByLabelText('Unidades da linha 1')).toBeVisible();
  });
  it('troca o detalhe no painel inferior sem inserir linhas na planilha ou gravar a seleção', async () => {
    const { w, repository } = fixture();
    w.services.push({ ...w.services[0], id: 's2', item: '1.2', description: 'Detectores' });
    w.entries = [
      { projectId: 'p', measurementId: 'm1', serviceId: 's', rows: [{ id: 'plates', location: '', comment: 'Placas no térreo', formula: 'STANDARD', multiplier: 3, measuredQuantity: 0, origin: { kind: 'manual' } }] },
      { projectId: 'p', measurementId: 'm1', serviceId: 's2', rows: [{ id: 'detectors', location: '', comment: 'Detectores na cobertura', formula: 'STANDARD', multiplier: 5, measuredQuantity: 0, origin: { kind: 'manual' } }] },
    ];
    render(<MeasurementWorkspace repository={repository} actor={actor}/>);
    const sheet = await screen.findByRole('region', { name: 'Planilha da medição atual' });
    const detail = screen.getByRole('region', { name: 'Painel inferior de quantitativos' });
    const rowCount = within(sheet).getAllByRole('row').length;
    expect(detail).toHaveTextContent(/^$/);
    expect(screen.getByRole('separator', { name: 'Ajustar altura da planilha e do detalhe' })).toBeInTheDocument();
    await act(async () => { fireEvent.click(screen.getByLabelText('Quantidade de Placas')); });
    expect(within(detail).getByLabelText('Comentário da linha 1')).toHaveValue('Placas no térreo');
    expect(within(sheet).queryByLabelText('Unidades da linha 1')).not.toBeInTheDocument();
    await act(async () => { fireEvent.click(screen.getByLabelText('Quantidade de Detectores')); });
    expect(within(detail).getByLabelText('Comentário da linha 1')).toHaveValue('Detectores na cobertura');
    expect(within(detail).getByLabelText('Unidades da linha 1')).toHaveValue(5);
    expect(within(sheet).getAllByRole('row')).toHaveLength(rowCount);
    fireEvent.change(screen.getByLabelText('Medição selecionada'), { target: { value: 'm2' } });
    expect(detail).toHaveTextContent(/^$/);
    expect(repository.commit).not.toHaveBeenCalled();
  });
  it('abre o detalhe somente pela medição atual e soma períodos sem editar o contrato ou o acumulado', async () => {
    const { w, repository } = fixture();
    w.entries = [{ projectId: 'p', measurementId: 'm1', serviceId: 's', rows: [{ id: 'original', location: '', comment: 'Primeira medição', formula: 'STANDARD', multiplier: 7, measuredQuantity: 0, origin: { kind: 'manual' } }] }];
    render(<MeasurementWorkspace repository={repository} actor={actor}/>);
    const selector = await screen.findByLabelText('Medição selecionada');
    fireEvent.change(selector, { target: { value: 'm2' } });
    const row = screen.getByTestId('service-s');
    const cells = within(row).getAllByRole('cell');
    expect(cells[5]).toHaveTextContent('100');
    expect(cells[11]).toHaveTextContent('7');
    for (const index of [3, 5, 6, 7, 8, 10, 11, 12, 13, 14]) {
      if (index !== 3) expect(within(cells[index]).queryByRole('button')).not.toBeInTheDocument();
      fireEvent.click(cells[index]);
      expect(screen.queryByLabelText('Unidades da linha 1')).not.toBeInTheDocument();
    }
    expect(within(cells[9]).queryByRole('button')).not.toBeInTheDocument();
    const detail = within(cells[9]).getByLabelText('Quantidade de Placas');
    fireEvent.click(detail);
    expect(screen.getByText('Detalhe de quantitativos · 2ª medição')).toBeVisible();
    const a = screen.getByLabelText('Unidades da linha 1');
    fireEvent.change(a, { target: { value: '3' } }); fireEvent.blur(a);
    await waitFor(() => expect(screen.getByLabelText('Quantidade de Placas')).toHaveValue(3));
    expect(cells[5]).toHaveTextContent('100');
    expect(cells[11]).toHaveTextContent('10');
    expect(screen.getByTestId('monthly-value')).toHaveTextContent('37,50');
    const saved = vi.mocked(repository.commit).mock.calls.at(-1)![0];
    expect(saved.entries.find(e => e.measurementId === 'm1')?.rows[0].multiplier).toBe(7);
    expect(saved.entries.find(e => e.measurementId === 'm2')?.rows[0].multiplier).toBe(3);
    expect(saved.services[0].contracted).toBe(100);
    expect(saved.entries.find(e => e.measurementId === 'm2')?.rows[0].id).not.toBe('__new__');
    fireEvent.change(selector, { target: { value: 'm1' } });
    expect(screen.getByLabelText('Quantidade de Placas')).toHaveValue(7);
  });
  it('preserva digitação até blur e permite trocar de período durante a gravação', async () => {
    const { repository } = fixture(); let confirm!: (w: Workspace) => void;
    vi.mocked(repository.commit).mockImplementation(() => new Promise(resolve => { confirm = resolve; }));
    render(<MeasurementWorkspace repository={repository} actor={actor}/>);
    const input = await screen.findByLabelText('Quantidade de Placas');
    fireEvent.change(input, { target: { value: '3' } });
    expect(repository.commit).not.toHaveBeenCalled();
    await waitFor(() => expect(repository.writeDraft).toHaveBeenCalledWith(expect.objectContaining({ measurementId: 'm1', serviceId: 's', changes: { multiplier: '3' } })));
    fireEvent.blur(input);
    const selector = screen.getByLabelText('Medição selecionada');
    expect(selector).toBeEnabled();
    fireEvent.change(selector, { target: { value: 'm2' } });
    expect(selector).toHaveValue('m2');
    const candidate = vi.mocked(repository.commit).mock.calls[0][0];
    expect(candidate.entries[0]).toMatchObject({ projectId: 'p', measurementId: 'm1', serviceId: 's' });
    await act(async () => confirm(candidate));
    await waitFor(() => expect(selector).toBeEnabled());
    expect(screen.getByTestId('monthly-value')).toHaveTextContent('0,00');
    fireEvent.change(selector, { target: { value: 'm1' } });
    expect(screen.getByTestId('monthly-value')).toHaveTextContent('37,50');
    fireEvent.change(selector, { target: { value: 'm2' } });
    expect(screen.getByLabelText('Quantidade de Placas')).toHaveValue(0);
    expect(screen.getByTestId('monthly-value')).toHaveTextContent('0,00');
  });
  it('permite alternar tarefas durante salvamentos lentos e confirma cada quantitativo em ordem', async () => {
    const { w, repository } = fixture();
    w.services.push({ ...w.services[0], id: 's2', item: '1.2', description: 'Detectores' });
    const confirmations: Array<(saved: Workspace) => void> = [];
    vi.mocked(repository.commit).mockImplementation(candidate => new Promise(resolve => {
      confirmations.push(() => resolve(candidate));
    }));
    render(<MeasurementWorkspace repository={repository} actor={actor}/>);
    const plates = await screen.findByRole('spinbutton', { name: 'Quantidade de Placas' });
    const detectors = screen.getByRole('spinbutton', { name: 'Quantidade de Detectores' });
    fireEvent.change(plates, { target: { value: '3' } });
    fireEvent.blur(plates);
    await waitFor(() => expect(repository.commit).toHaveBeenCalledTimes(1));
    expect(screen.getByText('Salvando…')).toBeVisible();

    // Navigation and the next local edit must not wait for the first HTTP reply.
    fireEvent.click(detectors);
    expect(screen.getByText('Detalhe de quantitativos · 1ª medição')).toBeVisible();
    fireEvent.change(detectors, { target: { value: '5' } });
    fireEvent.blur(detectors);
    expect(detectors).toHaveValue(5);
    expect(repository.commit).toHaveBeenCalledTimes(1);

    await act(async () => confirmations.shift()!());
    await waitFor(() => expect(repository.commit).toHaveBeenCalledTimes(2));
    await act(async () => confirmations.shift()!());
    await waitFor(() => expect(screen.getByText('Salvo neste navegador')).toBeVisible());
    const saved = vi.mocked(repository.commit).mock.calls.at(-1)![0];
    expect(saved.entries.find(e => e.serviceId === 's')?.rows[0].multiplier).toBe(3);
    expect(saved.entries.find(e => e.serviceId === 's2')?.rows[0].multiplier).toBe(5);
  });
  it('confirma boletim, detalhe e nova medição em sequência mesmo quando o primeiro salvamento demora', async () => {
    const { w, repository } = fixture();
    w.periods = [{ id: 'm1', number: 1, startDate: '2026-08-24', endDate: '2026-09-29', status: 'draft' }];
    w.entries = [{ projectId: 'p', measurementId: 'm1', serviceId: 's', rows: [{ id: 'r', location: '', comment: '', formula: 'STANDARD', multiplier: 1, measuredQuantity: 0 }] }];
    const confirmations: Array<() => void> = [];
    vi.mocked(repository.commit).mockImplementation(candidate => new Promise(resolve => confirmations.push(() => resolve(candidate))));
    render(<MeasurementWorkspace repository={repository} actor={actor}/>);
    const bulletin = await screen.findByRole('button', { name: /Boletim de Medição para Pagamento/ });
    fireEvent.click(bulletin);
    const art = screen.getByLabelText('Nº da ART');
    fireEvent.change(art, { target: { value: 'ART confirmada' } }); fireEvent.blur(art);
    await waitFor(() => expect(repository.commit).toHaveBeenCalledTimes(1));
    const quantity = screen.getByLabelText('Quantidade de Placas');
    fireEvent.change(quantity, { target: { value: '3' } }); fireEvent.blur(quantity);
    fireEvent.click(screen.getByRole('button', { name: 'Nova medição' }));
    fireEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Criar medição' }));
    expect(repository.commit).toHaveBeenCalledTimes(1);
    await act(async () => confirmations.shift()!());
    await waitFor(() => expect(repository.commit).toHaveBeenCalledTimes(2));
    await act(async () => confirmations.shift()!());
    await waitFor(() => expect(repository.commit).toHaveBeenCalledTimes(3));
    await act(async () => confirmations.shift()!());
    const saved = vi.mocked(repository.commit).mock.calls.at(-1)![0];
    expect(saved.periods).toHaveLength(2);
    expect(saved.entries[0].rows[0].multiplier).toBe(3);
    expect(saved.periods[0].bulletin?.contract.artNumber).toBe('ART confirmada');
  });
  it('serializa detalhe, boletim e criação de medição sem perder nenhuma alteração', async () => {
    const { w, repository } = fixture();
    w.periods = [{ id: 'm1', number: 1, startDate: '2026-08-24', endDate: '2026-09-29', status: 'draft' }];
    const confirmations: Array<() => void> = [];
    vi.mocked(repository.commit).mockImplementation(candidate => new Promise(resolve => confirmations.push(() => resolve(candidate))));
    render(<MeasurementWorkspace repository={repository} actor={actor}/>);
    const quantity = await screen.findByLabelText('Quantidade de Placas');
    fireEvent.change(quantity, { target: { value: '3' } }); fireEvent.blur(quantity);
    await waitFor(() => expect(repository.commit).toHaveBeenCalledTimes(1));
    fireEvent.click(screen.getByRole('button', { name: /Boletim de Medição para Pagamento/ }));
    const art = screen.getByLabelText('Nº da ART');
    fireEvent.change(art, { target: { value: 'ART após fila' } }); fireEvent.blur(art);
    fireEvent.click(screen.getByRole('button', { name: 'Nova medição' }));
    fireEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Criar medição' }));
    expect(repository.commit).toHaveBeenCalledTimes(1);
    await act(async () => confirmations.shift()!());
    await waitFor(() => expect(repository.commit).toHaveBeenCalledTimes(2));
    await act(async () => confirmations.shift()!());
    await waitFor(() => expect(repository.commit).toHaveBeenCalledTimes(3));
    await act(async () => confirmations.shift()!());
    const saved = vi.mocked(repository.commit).mock.calls[2][0];
    expect(saved.periods).toHaveLength(2);
    expect(saved.entries.find(entry => entry.measurementId === 'm1')?.rows[0].multiplier).toBe(3);
    expect(saved.periods[0].bulletin?.contract.artNumber).toBe('ART após fila');
    expect(vi.mocked(repository.commit).mock.calls.map(([, revision]) => revision)).toEqual([0, 1, 2]);
  });
  it('não anuncia confirmação quando o repositório falha e mantém a troca livre', async () => {
    const { repository } = fixture(); vi.mocked(repository.commit).mockRejectedValue(new Error('Sem conexão: rascunho preservado'));
    render(<MeasurementWorkspace repository={repository} actor={actor}/>);
    const input = await screen.findByLabelText('Quantidade de Placas');
    fireEvent.change(input, { target: { value: '3' } }); fireEvent.blur(input);
    await screen.findByText('Não salvo · rascunho preservado');
    expect(screen.getByLabelText('Medição selecionada')).toBeEnabled();
    expect(screen.getByTestId('monthly-value')).toHaveTextContent('37,50');
    expect(screen.getByRole('button', { name: 'Tentar salvar' })).toBeVisible();
  });
  it('perfil de consulta não permite editar ou criar período', async () => {
    const { repository } = fixture(); render(<MeasurementWorkspace repository={repository} actor={{ ...actor, canEdit: false }}/>);
    const quantity = await screen.findByLabelText('Quantidade de Placas');
    expect(quantity).toHaveAttribute('readonly');
    await act(async () => { fireEvent.click(quantity); });
    expect(screen.getByText('Detalhe de quantitativos · 1ª medição')).toBeVisible();
    await act(async () => { fireEvent.blur(quantity); });
    expect(screen.getByRole('button', { name: 'Nova medição' })).toBeDisabled();
    expect(repository.commit).not.toHaveBeenCalled();
  });
});
