import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { forwardRef, useEffect } from 'react';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import PlanTakeoff from './PlanTakeoff';
import { readTakeoffs, saveTakeoffs, type TakeoffPlan } from '@/lib/planTakeoff';
vi.mock('@/lib/planTakeoff', async importOriginal => ({ ...await importOriginal<object>(), readTakeoffs: vi.fn(), saveTakeoffs: vi.fn(), confirmAtomicTakeoffCache: vi.fn() }));
vi.mock('./PlanCanvas', () => ({ default: forwardRef<HTMLButtonElement, { onPoint: (p: { x: number; y: number }) => void; onFinish?: () => void; onReady?: (ready: boolean) => void; plan: TakeoffPlan }>(function MockCanvas({ onPoint, onFinish, onReady, plan }, ref) { useEffect(() => { onReady?.(true); }, [onReady]); return <><button ref={ref} onClick={() => onPoint({ x: 1, y: 1 })}>Ponto de teste</button><button onClick={() => onPoint({ x: 4, y: 5 })}>Segundo ponto de teste</button><button onClick={onFinish}>Botão direito de teste</button><span data-testid="visible-measures">{plan.measures.map(measure => measure.id).join(',')}</span></>; }) }));
const example: TakeoffPlan = { id: 'p', name: 'Planta', floor: 'Térreo', chapterId: 'building-1', building: 'Prédio principal', file: new Blob(), kind: 'image', scales: {}, measures: [] };
beforeEach(() => { vi.mocked(readTakeoffs).mockResolvedValue([example]); vi.mocked(saveTakeoffs).mockReset().mockResolvedValue(); });
describe('teste independente de levantamento', () => {
  it('preserva os três pontos quando a transação da Produção falha, sem salvar a planta separadamente', async () => {
    const onUseMeasure = vi.fn().mockResolvedValue(false);
    const key = JSON.stringify(Array.from({length:3}, (_, i) => `00000000-0000-4000-8000-00000000000${i+1}`));
    render(<PlanTakeoff storageKey={key} readOnly={false} embedded chapterId="building-1" measureContext={{taskId:'t',logId:'l'}} onUseMeasure={onUseMeasure} />);
    fireEvent.click(await screen.findByRole('button', {name:'Contagem'}));
    for (let i = 0; i < 3; i++) fireEvent.click(screen.getByText('Ponto de teste'));
    fireEvent.click(screen.getByRole('button', {name:'Concluir traçado'}));
    await waitFor(() => expect(onUseMeasure).toHaveBeenCalled());
    expect(saveTakeoffs).not.toHaveBeenCalled();
    expect(screen.getByText('3 pontos')).toBeInTheDocument();
    expect(screen.getByRole('button', {name:'Concluir traçado'})).toBeEnabled();
  });
  it('remove somente a ocorrência sem tarefa, preserva planta e referências e permite desfazer', async () => {
    const orphan = { id: 'orphan', name: 'Contagem antiga', kind: 'count' as const, page: 1, points: [{ x: 1, y: 1 }, { x: 2, y: 2 }] };
    const linked = { ...orphan, id: 'linked', name: 'Referência antiga' };
    const assigned = { ...orphan, id: 'assigned', name: 'Outra tarefa', taskId: 'other', logId: 'yesterday' };
    let saved = [{ ...example, measures: [orphan, linked, assigned] }];
    vi.mocked(readTakeoffs).mockImplementation(async () => saved);
    vi.mocked(saveTakeoffs).mockImplementation(async (_key, next) => { saved = next as typeof saved; });
    const onDeleteMeasure = vi.fn();
    const props = { storageKey: 'obra', readOnly: false, embedded: true, chapterId: 'building-1', protectedMeasureIds: ['linked'], measureContext: { taskId: 'current', logId: 'today' }, onDeleteMeasure };
    const view = render(<PlanTakeoff {...props} />);
    fireEvent.click(await screen.findByRole('button', { name: 'Gerenciar plantas' }));
    expect(screen.queryByRole('button', { name: 'Remover ocorrência Referência antiga' })).not.toBeInTheDocument();
    expect(screen.queryByText('Outra tarefa')).not.toBeInTheDocument();
    fireEvent.click(screen.getByRole('button', { name: 'Remover ocorrência Contagem antiga' }));
    await waitFor(() => expect(saved[0].measures).toEqual([linked, assigned]));
    expect(saved[0].file).toBe(example.file);
    expect(onDeleteMeasure).not.toHaveBeenCalled();
    fireEvent.click(screen.getByRole('button', { name: 'Aceitar gestão de desenhos' }));
    fireEvent.click(screen.getByRole('button', { name: 'Desfazer' }));
    await waitFor(() => expect(saved[0].measures).toEqual([orphan, linked, assigned]));
    fireEvent.click(screen.getByRole('button', { name: 'Gerenciar plantas' }));
    fireEvent.click(screen.getByRole('button', { name: 'Remover ocorrência Contagem antiga' }));
    await waitFor(() => expect(saved[0].measures).toEqual([linked, assigned]));
    view.unmount();
    render(<PlanTakeoff {...props} />);
    fireEvent.click(await screen.findByRole('button', { name: 'Gerenciar plantas' }));
    expect(screen.queryByRole('button', { name: 'Remover ocorrência Contagem antiga' })).not.toBeInTheDocument();
    expect(screen.getByRole('button', { name: 'Apagar planta Planta' })).toBeDisabled();
  });
  it('não permite limpar ocorrências no modo de consulta', async () => {
    vi.mocked(readTakeoffs).mockResolvedValue([{ ...example, measures: [{ id: 'orphan', name: 'Antiga', kind: 'count', page: 1, points: [{ x: 1, y: 1 }] }] }]);
    render(<PlanTakeoff storageKey="obra" readOnly embedded chapterId="building-1" />);
    fireEvent.click(await screen.findByRole('button', { name: 'Gerenciar plantas' }));
    expect(screen.queryByRole('button', { name: 'Remover ocorrência Antiga' })).not.toBeInTheDocument();
    expect(saveTakeoffs).not.toHaveBeenCalled();
  });
  it('bloqueia a gravação de captura na Produção sem tarefa e dia', async () => {
    render(<PlanTakeoff storageKey="obra" readOnly={false} embedded chapterId="building-1" onUseMeasure={vi.fn()} />);
    await waitFor(() => expect(screen.getByRole('button', { name: 'Contagem' })).toBeEnabled());
    fireEvent.click(screen.getByRole('button', { name: 'Contagem' }));
    fireEvent.click(screen.getByText('Ponto de teste'));
    fireEvent.click(screen.getByRole('button', { name: 'Concluir traçado' }));
    expect(await screen.findByText(/Abra a planta pela célula de um lançamento/)).toBeInTheDocument();
    expect(saveTakeoffs).not.toHaveBeenCalled();
  });
  it('retira o comando antigo de uso no detalhe da tabela independente', async () => {
    vi.mocked(readTakeoffs).mockResolvedValueOnce([{ ...example, measures: [{ id: 'placas', name: 'Placas executadas', kind: 'count', page: 1, points: [{ x: 1, y: 2 }, { x: 3, y: 4 }] }] }]);
    render(<PlanTakeoff storageKey="user/project" readOnly={false} />);
    await screen.findByText('2 un');
    expect(screen.queryByRole('button', { name: 'Usar no detalhe' })).not.toBeInTheDocument();
  });
  it('no modal da Produção conclui a contagem direto na célula e oculta a tabela inferior', async () => {
    const onUseMeasure = vi.fn().mockReturnValue(true);
    render(<PlanTakeoff storageKey="user/project" readOnly={false} embedded chapterId="building-1" measureContext={{ taskId: 'task-1', logId: 'day-1' }} allowedKinds={['count']} destinationColumn="A" onUseMeasure={onUseMeasure} />);
    await screen.findByRole('button', { name: 'Contagem' });
    expect(screen.getByText('A · Captura livre')).toBeInTheDocument();
    expect(screen.queryByRole('region', { name: 'Detalhe dos levantamentos' })).not.toBeInTheDocument();
    expect(screen.getByRole('button', { name: 'Gerenciar plantas' })).toBeInTheDocument();
    expect(screen.getByRole('button', { name: 'Comprimento poligonal' })).toBeDisabled();
    fireEvent.click(screen.getByRole('button', { name: 'Contagem' }));
    fireEvent.click(screen.getByText('Ponto de teste'));
    fireEvent.click(screen.getByText('Ponto de teste'));
    fireEvent.click(screen.getByText('Ponto de teste'));
    fireEvent.click(screen.getByRole('button', { name: 'Concluir traçado' }));
    await waitFor(() => expect(onUseMeasure).toHaveBeenCalledWith(expect.objectContaining({ id: 'p' }), expect.objectContaining({ kind: 'count', points: [{ x: 1, y: 1 }, { x: 1, y: 1 }, { x: 1, y: 1 }] }), 3, expect.objectContaining({ id: 'p' })));
    expect(screen.getByText('Salvo no navegador')).toBeInTheDocument();
    expect(saveTakeoffs).toHaveBeenCalledWith('user/project', expect.arrayContaining([expect.objectContaining({ measures: [expect.objectContaining({ kind: 'count', taskId: 'task-1', logId: 'day-1' })] })]), [example]);
  });
  it('conclui pelo botão direito e mantém a ferramenta ativa para a próxima linha', async () => {
    const onUseMeasure = vi.fn().mockReturnValue(true);
    render(<PlanTakeoff storageKey="user/project" readOnly={false} embedded chapterId="building-1" measureContext={{ taskId: 'task-1', logId: 'day-1' }} allowedKinds={['count']} onUseMeasure={onUseMeasure} />);
    fireEvent.click(await screen.findByRole('button', { name: 'Contagem' }));
    fireEvent.click(screen.getByText('Ponto de teste'));
    fireEvent.click(screen.getByText('Ponto de teste'));
    fireEvent.click(screen.getByText('Botão direito de teste'));
    await waitFor(() => expect(onUseMeasure).toHaveBeenCalledWith(expect.anything(), expect.objectContaining({ kind: 'count', points: [{ x: 1, y: 1 }, { x: 1, y: 1 }] }), 2, expect.objectContaining({ id: 'p' })));
    expect(screen.getByRole('button', { name: 'Contagem' })).toHaveAttribute('aria-pressed', 'true');
    expect(screen.getByText('0 pontos')).toBeInTheDocument();
  });
  it('desfaz a nova marcação quando o detalhe recusa a quantidade', async () => {
    const onUseMeasure = vi.fn().mockReturnValue(false);
    render(<PlanTakeoff storageKey="user/project" readOnly={false} embedded chapterId="building-1" measureContext={{ taskId: 'task-1', logId: 'day-1' }} allowedKinds={['count']} onUseMeasure={onUseMeasure} />);
    fireEvent.click(await screen.findByRole('button', { name: 'Contagem' }));
    fireEvent.click(screen.getByText('Ponto de teste'));
    fireEvent.click(screen.getByText('Botão direito de teste'));
    await waitFor(() => expect(saveTakeoffs).toHaveBeenCalledTimes(2));
    expect(saveTakeoffs).toHaveBeenLastCalledWith('user/project', [example], expect.arrayContaining([expect.objectContaining({ measures: [expect.objectContaining({ kind: 'count' })] })]));
    expect(screen.getByText('1 ponto')).toBeInTheDocument();
  });
  it('permite reutilizar uma contagem já salva sem reabrir a tabela inferior', async () => {
    const onUseMeasure = vi.fn().mockReturnValue(true);
    vi.mocked(readTakeoffs).mockResolvedValueOnce([{ ...example, measures: [{ id: 'placas', name: 'Placas executadas', kind: 'count', page: 1, points: [{ x: 1, y: 2 }, { x: 3, y: 4 }, { x: 5, y: 6 }] }] }]);
    render(<PlanTakeoff storageKey="user/project" readOnly={false} embedded chapterId="building-1" measureContext={{ taskId: 'task-1', logId: 'day-1' }} linkedMeasureIds={['placas']} focusMeasure={{ planId: 'p', page: 1, measureId: 'placas' }} onUseMeasure={onUseMeasure} />);
    fireEvent.click(await screen.findByRole('button', { name: 'Usar marcação selecionada' }));
    await waitFor(() => expect(onUseMeasure).toHaveBeenCalledWith(expect.objectContaining({ id: 'p' }), expect.objectContaining({ id: 'placas', taskId: 'task-1', logId: 'day-1' }), 3, expect.objectContaining({ id: 'p' })));
    expect(saveTakeoffs).toHaveBeenCalledWith('user/project', expect.arrayContaining([expect.objectContaining({ measures: [expect.objectContaining({ id: 'placas', taskId: 'task-1', logId: 'day-1' })] })]), expect.any(Array));
    expect(screen.queryByRole('region', { name: 'Detalhe dos levantamentos' })).not.toBeInTheDocument();
    expect(screen.getByRole('button', { name: 'Excluir marcação selecionada' })).toBeInTheDocument();
  });
  it('abre a mesma planta em tarefas diferentes sem mostrar os pontos da outra tarefa', async () => {
    let saved = [example];
    vi.mocked(readTakeoffs).mockImplementation(async () => saved);
    vi.mocked(saveTakeoffs).mockImplementation(async (_key, plans) => { saved = plans; });
    const first = render(<PlanTakeoff storageKey="obra" readOnly={false} embedded chapterId="building-1" measureContext={{ taskId: 'tarefa-a', logId: 'dia-1' }} onUseMeasure={vi.fn().mockReturnValue(true)} />);
    await waitFor(() => expect(screen.getByRole('button', { name: 'Contagem' })).toBeEnabled());
    fireEvent.click(screen.getByRole('button', { name: 'Contagem' }));
    fireEvent.click(screen.getByText('Ponto de teste'));
    fireEvent.click(screen.getByRole('button', { name: 'Concluir traçado' }));
    await waitFor(() => expect(saved[0].measures).toHaveLength(1));
    first.unmount();
    render(<PlanTakeoff storageKey="obra" readOnly={false} embedded chapterId="building-1" measureContext={{ taskId: 'tarefa-b', logId: 'dia-1' }} onUseMeasure={vi.fn().mockReturnValue(true)} />);
    await screen.findByRole('button', { name: 'Contagem' });
    expect(screen.getByTestId('visible-measures')).toBeEmptyDOMElement();
    expect(screen.getByRole('combobox', { name: 'Planta' })).toHaveValue('p');
  });
  it('cadastra a planta na janela e compartilha o capítulo entre tarefas', async () => {
    let saved: TakeoffPlan[] = [];
    vi.mocked(readTakeoffs).mockImplementation(async () => saved);
    vi.mocked(saveTakeoffs).mockImplementation(async (_key, next) => { saved = next; });
    const first = render(<PlanTakeoff storageKey="obra" readOnly={false} embedded chapterId="building-1" measureContext={{ taskId: 'tarefa-a', logId: 'dia-1' }} />);
    fireEvent.click(await screen.findByRole('button', { name: 'Gerenciar plantas' }));
    expect(screen.getByRole('dialog', { name: 'Gestão de desenhos' })).toBeInTheDocument();
    fireEvent.click(screen.getByRole('button', { name: 'Nova planta' }));
    fireEvent.change(screen.getByRole('textbox', { name: 'Pavimento da nova prancha' }), { target: { value: 'Térreo' } });
    fireEvent.change(screen.getByLabelText('Adicionar prancha'), { target: { files: [new File(['DXF'], 'PPCI.dxf')] } });
    await waitFor(() => expect(saved).toHaveLength(1));
    expect(saved[0]).toMatchObject({ name: 'PPCI.dxf', chapterId: 'building-1', floor: 'Térreo', measures: [] });
    first.unmount();
    render(<PlanTakeoff storageKey="obra" readOnly={false} embedded chapterId="building-1" measureContext={{ taskId: 'tarefa-b', logId: 'dia-1' }} />);
    expect(await screen.findByRole('combobox', { name: 'Planta' })).toHaveValue(saved[0].id);
  });
  it('apaga planta sem marcações e preserva outra planta do capítulo', async () => {
    const other = { ...example, id: 'outro', name: 'Cobertura' };
    vi.mocked(readTakeoffs).mockResolvedValueOnce([example, other]);
    render(<PlanTakeoff storageKey="obra" readOnly={false} embedded chapterId="building-1" />);
    fireEvent.click(await screen.findByRole('button', { name: 'Gerenciar plantas' }));
    fireEvent.click(screen.getByRole('button', { name: 'Apagar planta Planta' }));
    expect(saveTakeoffs).not.toHaveBeenCalled();
    fireEvent.click(screen.getByRole('button', { name: 'Confirmar exclusão da planta' }));
    await waitFor(() => expect(saveTakeoffs).toHaveBeenCalledWith('obra', [other], [example, other]));
    fireEvent.click(screen.getByRole('button', { name: 'Aceitar gestão de desenhos' }));
    expect(screen.getByRole('combobox', { name: 'Planta' })).toHaveValue('outro');
  });
  it('não apaga uma planta com marcações usadas na Produção', async () => {
    vi.mocked(readTakeoffs).mockResolvedValueOnce([{ ...example, measures: [{ id: 'usada', name: 'Placas', kind: 'count', page: 1, points: [{ x: 1, y: 1 }], taskId: 'tarefa-a', logId: 'dia-1' }] }]);
    render(<PlanTakeoff storageKey="obra" readOnly={false} embedded chapterId="building-1" />);
    fireEvent.click(await screen.findByRole('button', { name: 'Gerenciar plantas' }));
    expect(screen.getByRole('button', { name: 'Apagar planta Planta' })).toBeDisabled();
    expect(screen.getByText(/Exclusão bloqueada: esta prancha possui marcações/)).toBeInTheDocument();
    expect(saveTakeoffs).not.toHaveBeenCalled();
  });
  it('mantém consulta às plantas sem cadastro nem exclusão para visualizador', async () => {
    render(<PlanTakeoff storageKey="obra" readOnly embedded chapterId="building-1" />);
    fireEvent.click(await screen.findByRole('button', { name: 'Gerenciar plantas' }));
    expect(screen.queryByLabelText('Adicionar prancha')).not.toBeInTheDocument();
    expect(screen.queryByRole('button', { name: 'Apagar planta Planta' })).not.toBeInTheDocument();
    expect(screen.getByRole('button', { name: 'Planta · Térreo' })).toBeInTheDocument();
  });
  it('abre uma janela sobre o desenho e só aplica seleção e visibilidade ao aceitar', async () => {
    vi.mocked(readTakeoffs).mockResolvedValueOnce([example, { ...example, id: 'subsolo', name: 'Subsolo' }]);
    render(<PlanTakeoff storageKey="obra" readOnly={false} embedded chapterId="building-1" />);
    fireEvent.click(await screen.findByRole('button', { name: 'Lista de plantas' }));
    const dialog = screen.getByRole('dialog', { name: 'Gestão de desenhos' });
    expect(dialog.closest('section')).toBeNull();
    expect(screen.getByRole('columnheader', { name: 'Visível' })).toBeInTheDocument();
    expect(screen.getByRole('columnheader', { name: 'Eliminável' })).toBeInTheDocument();
    fireEvent.click(screen.getByRole('button', { name: 'Subsolo · Térreo' }));
    fireEvent.click(screen.getByRole('checkbox', { name: 'Visível Subsolo' }));
    fireEvent.click(screen.getByRole('button', { name: 'Cancelar gestão de desenhos' }));
    expect(screen.getByRole('combobox', { name: 'Planta' })).toHaveValue('p');
    fireEvent.click(screen.getByRole('button', { name: 'Lista de plantas' }));
    expect(screen.getByRole('checkbox', { name: 'Visível Subsolo' })).toBeChecked();
    fireEvent.click(screen.getByRole('button', { name: 'Subsolo · Térreo' }));
    fireEvent.click(screen.getByRole('button', { name: 'Aceitar gestão de desenhos' }));
    expect(screen.queryByRole('dialog', { name: 'Gestão de desenhos' })).not.toBeInTheDocument();
    expect(screen.getByRole('combobox', { name: 'Planta' })).toHaveValue('subsolo');
    expect(saveTakeoffs).not.toHaveBeenCalled();
  });
  it('não revela pontos antigos sem vínculo, de outra tarefa ou de outro dia após recarregar', async () => {
    const saved = [{ ...example, measures: [
      { id: 'antigo', name: 'Antigo', kind: 'count' as const, page: 1, points: [{ x: 1, y: 1 }] },
      { id: 'outro', name: 'Outra tarefa', kind: 'count' as const, page: 1, points: [{ x: 2, y: 2 }], taskId: 'outra', logId: 'hoje' },
      { id: 'ontem', name: 'Outro dia', kind: 'count' as const, page: 1, points: [{ x: 3, y: 3 }], taskId: 'atual', logId: 'ontem' },
      { id: 'atual', name: 'Atual', kind: 'count' as const, page: 1, points: [{ x: 4, y: 4 }], taskId: 'atual', logId: 'hoje' },
    ] }];
    vi.mocked(readTakeoffs).mockResolvedValue(saved);
    const props = { storageKey: 'obra', readOnly: false, embedded: true, chapterId: 'building-1', measureContext: { taskId: 'atual', logId: 'hoje' } };
    const first = render(<PlanTakeoff {...props} />);
    await waitFor(() => expect(screen.getByTestId('visible-measures')).toHaveTextContent(/^atual$/));
    first.unmount();
    render(<PlanTakeoff {...props} />);
    await waitFor(() => expect(screen.getByTestId('visible-measures')).toHaveTextContent(/^atual$/));
    expect(saveTakeoffs).not.toHaveBeenCalled();
    expect(saved[0].measures).toHaveLength(4);
  });
  it('permite vincular planta antiga ao capítulo sem perder os pontos', async () => {
    const legacy = { ...example, id: 'antiga', name: 'Antiga.dxf', chapterId: undefined, measures: [{ id: 'pontos', name: 'Placas', kind: 'count' as const, page: 1, points: [{ x: 1, y: 2 }] }] };
    vi.mocked(readTakeoffs).mockResolvedValueOnce([legacy]);
    render(<PlanTakeoff storageKey="obra" readOnly={false} embedded chapterId="building-1" />);
    fireEvent.click(await screen.findByRole('button', { name: 'Gerenciar plantas' }));
    fireEvent.click(screen.getByRole('button', { name: 'Nova planta' }));
    fireEvent.change(screen.getByRole('textbox', { name: 'Pavimento da nova prancha' }), { target: { value: '1º pavimento' } });
    fireEvent.click(screen.getByRole('button', { name: 'Vincular Antiga.dxf a este prédio' }));
    await waitFor(() => expect(saveTakeoffs).toHaveBeenCalledWith('obra', [expect.objectContaining({ id: 'antiga', chapterId: 'building-1', floor: '1º pavimento', measures: legacy.measures })], [legacy]));
  });
  it('permite contagem, comprimento e área sem escala, com unidade do desenho identificada', async () => {
    render(<PlanTakeoff storageKey="user/project" readOnly={false} />);
    await screen.findByText('Nenhum levantamento nesta planta.');
    expect(screen.getByRole('button', { name: 'Comprimento poligonal' })).toBeEnabled();
    expect(screen.getByRole('button', { name: 'Superfície poligonal' })).toBeEnabled();
    expect(screen.getByText('Unidades do desenho')).toBeInTheDocument();
    fireEvent.click(screen.getByRole('button', { name: 'Contagem' }));
    fireEvent.click(screen.getByText('Ponto de teste'));
    fireEvent.click(screen.getByRole('button', { name: 'Concluir traçado' }));
    await screen.findByText('1 un');
    expect(saveTakeoffs).toHaveBeenCalledWith('user/project', expect.arrayContaining([expect.objectContaining({ measures: [expect.objectContaining({ kind: 'count', points: [{ x: 1, y: 1 }] })] })]), [example]);
    fireEvent.click(screen.getByRole('button', { name: 'Desfazer' }));
    await screen.findByText('Nenhum levantamento nesta planta.');
  });
  it('lança comprimento sem escala em qualquer coluna escolhida', async () => {
    const onUseMeasure = vi.fn().mockReturnValue(true);
    render(<PlanTakeoff storageKey="user/project" readOnly={false} embedded chapterId="building-1" measureContext={{ taskId: 'task-1', logId: 'day-1' }} destinationColumn="A" onUseMeasure={onUseMeasure} />);
    const length = await screen.findByRole('button', { name: 'Comprimento linear' });
    expect(length).toBeEnabled();
    expect(screen.getByText('A · Captura livre')).toBeInTheDocument();
    fireEvent.click(length);
    fireEvent.click(screen.getByText('Ponto de teste'));
    fireEvent.click(screen.getByText('Segundo ponto de teste'));
    await waitFor(() => expect(onUseMeasure).toHaveBeenCalledWith(expect.anything(), expect.objectContaining({ kind: 'linearLength' }), 5, expect.objectContaining({ id: 'p' })));
    expect(screen.getByRole('button', { name: 'Comprimento linear' })).toHaveAttribute('aria-pressed', 'true');
    expect(screen.getByText('0 pontos')).toBeInTheDocument();
    fireEvent.click(screen.getByText('Ponto de teste'));
    fireEvent.click(screen.getByText('Segundo ponto de teste'));
    await waitFor(() => expect(onUseMeasure).toHaveBeenCalledTimes(2));
  });
  it('não descarta dois pontos recusados pelo saldo nem duplica a conclusão', async () => {
    const onUseMeasure = vi.fn().mockReturnValue(false);
    render(<PlanTakeoff storageKey="user/project" readOnly={false} embedded chapterId="building-1" measureContext={{ taskId: 'task-1', logId: 'day-1' }} onUseMeasure={onUseMeasure} />);
    fireEvent.click(await screen.findByRole('button', { name: 'Comprimento linear' }));
    fireEvent.click(screen.getByText('Ponto de teste'));
    fireEvent.click(screen.getByText('Segundo ponto de teste'));
    fireEvent.click(screen.getByText('Botão direito de teste'));
    await waitFor(() => expect(saveTakeoffs).toHaveBeenCalledTimes(2));
    expect(onUseMeasure).toHaveBeenCalledOnce();
    expect(screen.getByText('2 pontos')).toBeInTheDocument();
    fireEvent.click(screen.getByText('Ponto de teste'));
    expect(screen.getByText('2 pontos')).toBeInTheDocument();
    expect(onUseMeasure).toHaveBeenCalledOnce();
  });
  it('preserva o traçado quando falha o salvamento e permite nova tentativa', async () => {
    vi.mocked(saveTakeoffs).mockRejectedValueOnce(new Error('quota'));
    render(<PlanTakeoff storageKey="failure" readOnly={false} />);
    await screen.findByText('Nenhum levantamento nesta planta.');
    fireEvent.click(screen.getByRole('button', { name: 'Contagem' }));
    fireEvent.click(screen.getByText('Ponto de teste'));
    fireEvent.click(screen.getByRole('button', { name: 'Concluir traçado' }));
    await screen.findByRole('alert');
    expect(screen.getByRole('button', { name: 'Concluir traçado' })).toBeEnabled();
    fireEvent.click(screen.getByRole('button', { name: 'Concluir traçado' }));
    await screen.findByText('1 un');
  });
  it('renomeia pela mesma validação da célula vinculada e reverte uma recusa', async () => {
    const measure = { id: 'placas', name: 'Placas executadas', kind: 'count' as const, page: 1, points: [{ x: 1, y: 2 }], taskId: 'task-1', logId: 'day-1' };
    const original = { ...example, measures: [measure] };
    vi.mocked(readTakeoffs).mockResolvedValueOnce([original]);
    const update = vi.fn().mockReturnValue(false);
    render(<PlanTakeoff storageKey="obra" readOnly={false} embedded chapterId="building-1" measureContext={{ taskId: 'task-1', logId: 'day-1' }} linkedMeasureIds={['placas']} focusMeasure={{ planId: 'p', page: 1, measureId: 'placas' }} onUpdateMeasure={update} />);
    const name = await screen.findByRole('textbox', { name: 'Renomear marcação selecionada' });
    fireEvent.change(name, { target: { value: 'Novo nome' } });
    expect(saveTakeoffs).not.toHaveBeenCalled();
    fireEvent.blur(name);
    await waitFor(() => expect(update).toHaveBeenCalledWith(expect.objectContaining({ id: 'p' }), expect.objectContaining({ name: 'Novo nome' }), 1, expect.objectContaining({ id: 'p' })));
    await waitFor(() => expect(saveTakeoffs).toHaveBeenLastCalledWith('obra', [original], expect.any(Array)));
    expect(screen.getByRole('textbox', { name: 'Renomear marcação selecionada' })).toHaveValue('Placas executadas');
  });
  it('visualizador não grava nem importa', async () => {
    render(<PlanTakeoff storageKey="viewer" readOnly />);
    await screen.findByText('Nenhum levantamento nesta planta.');
    expect(screen.getByLabelText('Adicionar planta')).toBeDisabled();
    expect(screen.getByRole('button', { name: 'Contagem' })).toBeDisabled();
    await waitFor(() => expect(saveTakeoffs).not.toHaveBeenCalled());
  });
});
