async page => {
await page.goto('http://127.0.0.1:5181/dev/measurement/index.html?test=acceptance-'+Date.now());
await page.setViewportSize({width:1600,height:1000});
await page.getByRole('button',{name:'Confirmar incorporação'}).click();
await page.getByRole('button',{name:'Detalhar quantidade da 1ª medição: Instalação de placas de sinalização'}).click();
await page.getByRole('button',{name:'Levantar coluna A da linha 1 na planta',exact:true}).click();
await page.getByRole('img',{name:'Planta e marcações'}).waitFor();
await page.getByRole('button',{name:'Contagem',exact:true}).click();
const drawing=page.getByRole('img',{name:'Planta e marcações'});
await drawing.click({position:{x:300,y:230}});await drawing.click({position:{x:500,y:300}});await drawing.click({position:{x:700,y:380}});
await page.getByRole('button',{name:'Concluir traçado'}).click();
await page.getByText('Planta e quantitativo salvos no navegador',{exact:true}).waitFor();
if(await page.locator('[data-measure-point]').count()!==3) throw new Error('Three marks missing');
await page.screenshot({path:'output/playwright/measurement-capture.png'});
await page.getByRole('button',{name:'Close',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});
if(await page.getByLabel('Unidades da linha 1',{exact:true}).inputValue()!=='3') throw new Error('A != 3');
if(!(await page.getByTestId('service-signs').innerText()).includes('37,50'))throw new Error('Incorrect monetary value');
await page.reload();await page.getByRole('button',{name:'Detalhar quantidade da 1ª medição: Instalação de placas de sinalização'}).click();
if(await page.getByLabel('Unidades da linha 1',{exact:true}).inputValue()!=='3') throw new Error('Reload quantity lost');
await page.getByRole('button',{name:'Levantar coluna A da linha 1 na planta',exact:true}).click();
await page.waitForFunction(()=>document.querySelectorAll('[data-measure-point]').length===3);
await page.getByRole('button',{name:'Close',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});
await page.screenshot({path:'output/playwright/measurement-workspace.png',fullPage:true});
if(await page.getByRole('dialog').count()){await page.getByRole('button',{name:'Close',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});await page.getByRole('dialog').waitFor({state:'hidden'});}
const assert=(ok,m)=>{if(!ok)throw new Error(m)};
const ready=()=>page.locator('[role=status]').filter({hasText:'Salvo neste navegador'}).first().waitFor();
const quantity=page.getByLabel('Quantidade de Repetidores de eventos para linhas endereçáveis',{exact:true});
await quantity.fill('29');await quantity.press('Enter');await ready();
assert((await page.getByTestId('service-repeaters').innerText()).includes('362,50'),'manual financial');
await page.getByLabel('Medição selecionada').selectOption('m2');
assert(await quantity.inputValue()==='0','period leakage');await quantity.fill('2');await quantity.press('Enter');await ready();
await page.getByLabel('Medição selecionada').selectOption('m3');await quantity.fill('3');await quantity.press('Enter');await ready();
assert((await page.getByTestId('service-repeaters').innerText()).includes('34'),'accumulated includes selected');
await page.getByLabel('Medição selecionada').selectOption('m1');
assert(await quantity.inputValue()==='29','lost first measurement');
await page.getByRole('button',{name:'Detalhar quantidade da 1ª medição: Detector de fumaça óptico endereçável'}).click();
await page.getByLabel('Unidades da linha 1',{exact:true}).fill('220');await page.getByLabel('Unidades da linha 1',{exact:true}).press('Enter');await ready();
assert((await page.getByTestId('service-detectors').innerText()).includes('2.750,00'),'preserved edit');
await page.getByRole('button',{name:'Excluir linha 1',exact:true}).click();await ready();
assert(await page.getByLabel('Quantidade de Detector de fumaça óptico endereçável',{exact:true}).inputValue()==='0','preserved delete');
await page.getByRole('button',{name:'Histórico',exact:true}).click();
const record=page.getByRole('dialog').locator('details').first();await record.locator('summary').click();
assert((await record.innerText()).includes('Dado preservado'),'recoverable before content');
await record.getByRole('button',{name:'Restaurar conteúdo anterior'}).click();await ready();
await page.getByRole('button',{name:'Close',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});await page.getByRole('dialog').waitFor({state:'hidden'});
assert(await page.getByLabel('Quantidade de Detector de fumaça óptico endereçável',{exact:true}).inputValue()==='220','restore failed');
await page.getByRole('button',{name:'Detalhar quantidade da 1ª medição: Repetidores de eventos para linhas endereçáveis'}).click();
await page.getByRole('button',{name:'Levantar coluna B da linha 1 na planta',exact:true}).click();
await page.getByRole('img',{name:'Planta e marcações'}).waitFor();
assert(await page.locator('[data-measure-point]').count()===0,'foreign service marks leaked');
await page.getByRole('button',{name:'Close',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});await page.getByRole('dialog').waitFor({state:'hidden'});
const xlsx=page.waitForEvent('download');await page.getByRole('button',{name:'Excel',exact:true}).click();await (await xlsx).saveAs('output/playwright/measurement-monthly.xlsx');
const pdf=page.waitForEvent('download');await page.getByRole('button',{name:'PDF',exact:true}).click();await (await pdf).saveAs('output/playwright/measurement-monthly.pdf');
await page.getByRole('button',{name:'Detalhar quantidade da 1ª medição: Instalação de placas de sinalização'}).click();
await page.screenshot({path:'output/playwright/measurement-workspace.png',fullPage:true});
return 'PASS capture, reload, monthly values, periods 1/2/3, preserved edit/delete/restore, isolation, PDF/XLSX';
}